dist: xenial
notifications:
    email: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -e .
    - pip list
script:
    - flake8 muffnn
    - py.test -vv muffnn
